# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# Fix for Windows file locking (JARs)
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dsun.zip.disableMemoryMapping=true
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.vfs.watch=false

# AndroidX and Kotlin settings
android.useAndroidX=true
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
android.nonTransitiveRClass=true
android.enableJetifier=true
android.nonFinalResIds=false
android.useLegacyPackaging=true

# Avoid Kotlin daemon leaks
kotlin.daemon.jvmargs=-Xmx512m -Dsun.zip.disableMemoryMapping=true
