# Project-wide Gradle settings.
# Fix for Windows file locking (JARs)
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dsun.zip.disableMemoryMapping=true -Dsun.io.useCanonCaches=false
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.vfs.watch=false
org.gradle.unsafe.configuration-cache=false
android.nonTransitiveRClass=true

# AndroidX and Kotlin settings
android.useAndroidX=true
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
android.enableJetifier=true
android.nonFinalResIds=false
android.useLegacyPackaging=true

# Avoid Kotlin daemon leaks
kotlin.daemon.jvmargs=-Xmx512m -Dsun.zip.disableMemoryMapping=true
